  --领用
--receive
  --创建表
  CREATE TABLE "PT_0911IR" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DLR_CD" VARCHAR2(255 BYTE), 
	"DLR_NM" VARCHAR2(255 BYTE), 
	"DELEGATE_TYPE" VARCHAR2(255 BYTE), 
	"PART_NUM" NUMBER, 
	"DELIVERY_AMT" NUMBER, 
	"COST_AMT" NUMBER, 
	"YEAR_MONTH" VARCHAR2(255 BYTE), 
	 CONSTRAINT "PT_0911IR_PK" PRIMARY KEY ("ID")
   )  ;

   COMMENT ON COLUMN "PT_0911IR"."DLR_CD" IS '经销商代码';
   COMMENT ON COLUMN "PT_0911IR"."DLR_NM" IS '经销商名称';
   COMMENT ON COLUMN "PT_0911IR"."DELEGATE_TYPE" IS '委托类型';
   COMMENT ON COLUMN "PT_0911IR"."PART_NUM" IS '配件数量';
   COMMENT ON COLUMN "PT_0911IR"."DELIVERY_AMT" IS '出库金额';
   COMMENT ON COLUMN "PT_0911IR"."COST_AMT" IS '成本金额';
   COMMENT ON COLUMN "PT_0911IR"."YEAR_MONTH" IS '年月';
   
--创建序列   
CREATE SEQUENCE DMSDB.SEQ_PT_0911IR
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
   

   
   
   