delete from PT_0911IS;

select * from PT_0911IS


  CREATE TABLE "PT_0912T" 
   (	"DLR_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ISOUT" VARCHAR2(20 BYTE), 
	"PARTRATE" NUMBER, 
	 CONSTRAINT "PT_0912T_PK" PRIMARY KEY ("DLR_CD")
   )  ;

   COMMENT ON COLUMN "PT_0912T"."DLR_CD" IS '经销商代码';
   COMMENT ON COLUMN "PT_0912T"."ISOUT" IS '是否出入库Y是N否';
   COMMENT ON COLUMN "PT_0912T"."PARTRATE" IS '配件税率';