select count(*) from  cm_0301t t where  t.CMM_GRP_CD='SER603';

select CMM_GRP_CD, CMM_GRP_CD_NM, REMARK, USE_YN, REG_USR_ID, REG_DT, UPDT_USR_ID, UPDT_DT, REMARK_TITLE_NM, SYS_CD_YN from CM_0301T where CMM_GRP_CD='WWW001';

DELETE from CM_0301T where CMM_GRP_CD='WWW001';

select CMM_GRP_CD, LANG_CD, CMM_GRP_CD_TXT, REG_USR_ID, REG_DT, UPDT_USR_ID, UPDT_DT, REMARK_TITLE_NM from CM_0302T where CMM_GRP_CD='WWW001';

DELETE from CM_0302T where CMM_GRP_CD='WWW001';

select CMM_CD, CMM_GRP_CD, CMM_CD_NM, REMARK1, REMARK2, REMARK3, REMARK4, REMARK5, REMARK6, REMARK7, REMARK8, REMARK9, REMARK10, USE_YN, SORT_ORDER, REG_USR_ID, REG_DT, UPDT_USR_ID, UPDT_DT from CM_0303T;

select CMM_CD, CMM_GRP_CD, CMM_CD_NM, REMARK1, REMARK2, REMARK3, REMARK4, REMARK5, REMARK6, REMARK7, REMARK8, REMARK9, REMARK10, USE_YN, SORT_ORDER, REG_USR_ID, REG_DT, UPDT_USR_ID, UPDT_DT from CM_0303T where CMM_GRP_CD='WWW001';

DELETE from CM_0303T where CMM_GRP_CD='WWW001';

select CMM_CD, LANG_CD, CMM_CD_TXT, REG_USR_ID, REG_DT, UPDT_USR_ID, UPDT_DT, CMM_GRP_CD from CM_0304T where CMM_GRP_CD='WWW001';