
  CREATE TABLE "DMSDB"."PT_0910T" 
   (	"YEARMONTH" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DLRFILLRATE" NUMBER(*,0), 
	"PARTRATE" NUMBER(*,0), 
	"CREATETIME" DATE, 
	"CREATENAME" VARCHAR2(50 BYTE), 
	"UPDATETIME" VARCHAR2(20 BYTE), 
	"UPDATENAME" VARCHAR2(20 BYTE), 
	"CREATEID" VARCHAR2(20 BYTE), 
	"UPDATEID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "W_OO2T_PK" PRIMARY KEY ("YEARMONTH")
   )  ;

   COMMENT ON COLUMN "DMSDB"."PT_0910T"."YEARMONTH" IS '月份';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."DLRFILLRATE" IS '经销商满足率';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."PARTRATE" IS '缺件率';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."CREATETIME" IS '创建时间';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."CREATENAME" IS '创建人姓名';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."UPDATETIME" IS '修改时间';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."UPDATENAME" IS '修改人姓名';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."CREATEID" IS '创建人ID';
   COMMENT ON COLUMN "DMSDB"."PT_0910T"."UPDATEID" IS '修改人ID';
