SELECT Y.ITEM_CD as itemcd,F.ITEM_NM as itemnm,Y.partItemNm as partItemNm,Y.ODR_LST_BO_QT as partNm,Y.BMP_PURC_PRC as partAmt,Y.BO_AVG_DAY as boavgday FROM (
select T.ITEM_CD,COUNT(T.ITEM_CD) AS partItemNm,SUM(ODR_LST_BO_QT) AS ODR_LST_BO_QT,SUM(BMP_PURC_PRC) AS BMP_PURC_PRC,SUM(BO_AVG_DAY) AS BO_AVG_DAY from(
select 
F.ITEM_CD--缺件编码
,F.ITEM_NM--缺件名称
,E.ODR_CFM_APL_FLG--
,E.ODR_LST_BO_QT----缺件数量
,round(E.BO_AVG_DAY,0) as BO_AVG_DAY--缺件时长
 ,(NVL((SELECT NVL(ROUND(LPR_LST_PRC * ( 1 + FN_GET_VAT(null,'ALL')),2),0)
  FROM PT_0218I T2
  WHERE (LPR_PNO,LPR_APL_DT) IN (
            SELECT LPR_PNO,
                   MAX(LPR_APL_DT) AS LPR_APL_DT
              FROM PT_0218I T3
          GROUP BY LPR_PNO)
   AND TRIM(T2.LPR_PNO) = E.ODR_CFM_PNO),0) * E.ODR_LST_BO_QT) AS BMP_PURC_PRC --缺件金额（单价*数量）
from (
SELECT
C.ODR_CFM_PNO,C.ODR_CFM_APL_FLG,C.ODR_LST_BO_QT,(CASE WHEN SUM(CASE WHEN NVL (C.ODR_LST_BO_QT, 0)>0 AND G.INVC_DT IS NULL AND D.OHR_ORD_RCVE_DT  IS NOT NULL  THEN 1 ELSE 0 END ) = 0 
THEN 0 ELSE 
SUM(CASE WHEN NVL (C.ODR_LST_BO_QT, 0)>0  AND G.INVC_DT IS NULL  AND D.OHR_ORD_RCVE_DT  IS NOT NULL THEN TO_NUMBER(SYSDATE-TO_DATE(D.OHR_ORD_RCVE_DT, 'yyyyMMdd')) ELSE 0 END) 
END) AS BO_AVG_DAY
FROM (
SELECT
A.OHR_ORD_NO
,A.OHR_ORD_RCVE_DT
,A.OHR_DLR_ORD_NO
,B.DLR_NM
,B.DLR_CD
FROM 
 (
    SELECT
    *
    FROM CM_0101T
    WHERE DMS_USE_YN = 'Y'
    -- AND  OPEN_DT <![CDATA[<=]]> TO_CHAR (SYSDATE, 'YYYYMMDD')
    AND OPEN_DT <= TO_CHAR(SYSDATE,'YYYYMMDD')   
) B INNER JOIN PT_0421I A
ON A.OHR_DLR_CD = B.DLR_CD
WHERE 1=1 
--<if test='sPurcRegDtFr != null'>
--	AND TO_DATE(OHR_ORD_RCVE_DT,'YYYY-MM-DD HH24:MI:SS') <![CDATA[>=]]> TO_DATE(TO_CHAR(#{sPurcRegDtFr},'YYYYMMDD'),'YYYY-MM-DD HH24:MI:SS')
--</if>
--<if test='sPurcRegDtTo != null'>
--	AND TO_DATE(OHR_ORD_RCVE_DT,'YYYY-MM-DD HH24:MI:SS') <![CDATA[<=]]> TO_DATE(TO_CHAR(#{sPurcRegDtTo},'YYYYMMDD'),'YYYY-MM-DD HH24:MI:SS')
--</if>
) D INNER JOIN  PT_0422I C
ON C.ODR_ODR_NO = D.OHR_ORD_NO
LEFT  JOIN (  SELECT INVC_DT,INR_ORD_LN,INR_ORD_NO FROM (
    SELECT
      DLR_CD
    FROM
      CM_0101T
    WHERE DMS_USE_YN = 'Y'
--       AND  OPEN_DT <![CDATA[<=]]> TO_CHAR (SYSDATE, 'YYYYMMDD')
      AND OPEN_DT <= TO_CHAR(SYSDATE,'YYYYMMDD')   
    ) M INNER JOIN 
        (SELECT
            INR_DLR_CD
            ,INR_ORD_NO
            ,INR_ORD_LN
            ,MAX(INR_INV_DT) AS INVC_DT
        FROM PT_0435I
        WHERE 1=1
        GROUP BY INR_DLR_CD, INR_ORD_NO, INR_ORD_LN
    ) N ON N.INR_DLR_CD = M.DLR_CD
		)G
ON C.ODR_ODR_NO = G.INR_ORD_NO AND C.ODR_ODR_LN = G.INR_ORD_LN
group by C.ODR_CFM_PNO,C.ODR_CFM_APL_FLG,C.ODR_LST_BO_QT
)E LEFT JOIN (
SELECT
ITEM_CD
,ITEM_NM
FROM PT_0201T
) F ON F.ITEM_CD = TRIM(E.ODR_CFM_PNO)
WHERE E.ODR_CFM_APL_FLG != 'N'
--  AND E.ODR_LST_BO_QT <![CDATA[>]]> 0
AND E.ODR_LST_BO_QT > 0
) T GROUP BY ITEM_CD
) Y LEFT JOIN (
SELECT
ITEM_CD
,ITEM_NM
FROM PT_0201T
) F ON F.ITEM_CD = Y.ITEM_CD;