SELECT A.* FROM PT_0502T A
LEFT JOIN PT_0201T B ON A.DLR_CD = B.DLR_CD AND A.ITEM_CD = B.ITEM_CD
LEFT JOIN SE_0300T R ON A.DLR_CD = R.DLR_CD AND A.RO_DOC_NO = R.RO_DOC_NO
LEFT JOIN PT_0301T C ON A.DLR_CD = C.DLR_CD AND A.ITEM_CD = C.ITEM_CD AND A.REQ_STRGE_CD = C.STRGE_CD
LEFT JOIN PT_0302T D ON A.DLR_CD = D.DLR_CD AND A.ITEM_CD = D.ITEM_CD AND A.REQ_STRGE_CD = D.STRGE_CD AND A.RESV_DOC_NO = D.RESV_DOC_NO AND A.RESV_DOC_LINE_NO = D.RESV_DOC_LINE_NO
LEFT JOIN PT_0511T E ON A.DLR_CD = E.DLR_CD AND A.RO_DOC_NO = E.RO_DOC_NO
LEFT JOIN PT_0512T F ON A.DLR_CD = F.DLR_CD AND A.PAR_REQ_DOC_NO = F.PAR_REQ_DOC_NO AND A.PAR_REQ_DOC_LINE_NO = F.PAR_REQ_DOC_LINE_NO
AND A.PAR_REQ_DOC_LINE_NO = F.GI_DOC_LINE_NO
AND A.PAR_REQ_STAT_CD = F.GI_DOC_STAT_CD
LEFT JOIN PT_0411T G ON A.DLR_CD = G.DLR_CD AND A.RO_DOC_NO = G.REF_DOC_NO AND A.RO_LINE_NO = G.REF_DOC_LINE_NO AND A.ITEM_CD = G.ITEM_CD
LEFT JOIN PT_0501T H ON A.DLR_CD = H.DLR_CD AND A.PAR_REQ_DOC_NO = H.PAR_REQ_DOC_NO
LEFT JOIN PT_0214T I ON A.DLR_CD = I.DLR_CD AND A.REQ_STRGE_CD = I.STRGE_CD AND A.ITEM_CD = I.ITEM_CD
LEFT JOIN PT_0208T J ON A.DLR_CD = J.DLR_CD AND A.REQ_STRGE_CD = J.STRGE_CD AND A.ITEM_CD = J.ITEM_CD
--LEFT JOIN PT_0224T K ON A.DLR_CD = K.DLR_CD  AND A.REQ_STRGE_CD = K.STRGE_CD AND A.ITEM_CD = K.ITEM_CD AND K.LOC_CD != ''
--LEFT JOIN PT_0231T L ON A.DLR_CD = L.DLR_CD AND A.PKG_ITEM_CD = L.PKG_ITEM_CD AND A.ITEM_CD = L.ITEM_CD AND A.PKG_DOC_NO = L.PKG_DOC_NO
LEFT JOIN CM_0801T K2 ON F.RECEIVE_ID = K2.USR_ID
LEFT JOIN CM_0801T K3 ON A.REG_USR_ID = K3.USR_ID
LEFT JOIN CM_3401T K4 ON K3.DEPT_CD = K4.DEPT_CD
LEFT JOIN CM_0801T K5 ON R.REG_USR_ID = K5.USR_ID
LEFT JOIN PT_0312T K6 ON K6.DLR_CD = F.DLR_CD AND K6.MVT_DOC_NO = F.MVT_DOC_NO AND K6.ITEM_CD = F.ITEM_CD;