select * from W_002T t ;


SELECT
D.OHR_DLR_CD AS DLR_CD
,D.DLR_NM AS DLR_NM
,D.OHR_ORD_NO AS BMP_ORD_NO
,D.OHR_DLR_ORD_NO AS PURC_ORD_NO
,E.ITEM_NM AS ITEM_NM
,C.ODR_CFM_PNO AS CONFIRM_PAR_NO
,C.ODR_LST_BO_QT AS BO_QTY
,D.OHR_ORD_RCVE_DT AS PURC_REG_DT
,C.ODR_UPCE_NDP + C.ODR_VAT_AMT AS BMP_PURC_PRC
,D.OHR_ORD_RCVE_DT AS CONFIRM_DT
,C.ODR_ETD AS ARRV_DT
,C.ODR_ODR_LN AS PURC_ORD_LINE_NO
,'03' AS PURC_ITEM_STAT_CD
,C.ODR_ALC_QT
,C.ODR_OPIC_QT
,C.ODR_OPAC_QT
,C.ODR_PAKD_QT
,C.ODR_INV_QT
FROM PT_0422I C INNER JOIN(
    SELECT
    A.*
    ,B.DLR_NM
    ,B.OPEN_DT
    FROM PT_0421I A INNER JOIN (
        SELECT
        *
        FROM CM_0101T
        WHERE DMS_USE_YN = 'Y'
        AND OPEN_DT <= TO_CHAR(SYSDATE,'YYYYMMDD')
    ) B
    ON A.OHR_DLR_CD = B.DLR_CD
) D 
ON C.ODR_ODR_NO = D.OHR_ORD_NO   
LEFT JOIN (
    SELECT
    ITEM_CD
    ,ITEM_NM
    FROM PT_0201T
) E ON E.ITEM_CD = TRIM(C.ODR_CFM_PNO)
WHERE C.ODR_CFM_APL_FLG != 'N'
AND C.ODR_LST_BO_QT > 0
ORDER BY D.OHR_DLR_CD ASC
         ,D.OHR_ORD_RCVE_DT DESC
         ,D.OHR_DLR_ORD_NO DESC
         ,C.ODR_ODR_LN ASC;
         
         
         
SELECT
D.DLR_CD AS DLR_CD--经销商代码
,D.OHR_ORD_NO AS BMP_ORD_NO--BMP订单编号
,D.OHR_DLR_ORD_NO AS PURC_ORD_NO--订单编号
,C.ODR_CFM_PNO AS CONFIRM_PAR_NO--配件编号
,E.ITEM_NM AS ITEM_NM--配件名字
,C.ODR_LST_BO_QT AS BO_QTY--缺件数量
,D.OHR_ORD_RCVE_DT AS PURC_REG_DT--传送日期
,C.ODR_UPCE_NDP + C.ODR_VAT_AMT AS BMP_PURC_PRC
,D.OHR_ORD_RCVE_DT AS CONFIRM_DT
,C.ODR_ETD AS ARRV_DT
,C.ODR_ODR_LN AS PURC_ORD_LINE_NO
,'03' AS PURC_ITEM_STAT_CD
,C.ODR_ALC_QT
,C.ODR_OPIC_QT
,C.ODR_OPAC_QT
,C.ODR_PAKD_QT
,C.ODR_INV_QT
FROM PT_0422T C INNER JOIN(
    SELECT
    A.*
    ,B.DLR_NM
    ,B.OPEN_DT
    FROM PT_0421T A INNER JOIN (
        SELECT
        *
        FROM CM_0101T
        WHERE DMS_USE_YN = 'Y'
        AND OPEN_DT <= TO_CHAR(SYSDATE,'YYYYMMDD')
    ) B
    ON A.DLR_CD = B.DLR_CD
) D 
ON C.ODR_ODR_NO = D.OHR_ORD_NO   
LEFT JOIN (
    SELECT
    ITEM_CD
    ,ITEM_NM
    FROM PT_0201T
) E ON E.ITEM_CD = TRIM(C.ODR_CFM_PNO)
WHERE C.ODR_CFM_APL_FLG != 'N'
AND C.ODR_LST_BO_QT > 0
ORDER BY D.DLR_CD ASC
         ,D.OHR_ORD_RCVE_DT DESC
         ,D.OHR_DLR_ORD_NO DESC
         ,C.ODR_ODR_LN ASC;
         
         
select * from PT_0422T;